version: '2'

services:
    db:
        image: mariadb:10.3.5
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    php:
        build: php7-fpm
        links:
          - db
          - redis
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ~/.composer:/var/www/.composer
            - ~/.ssh:/var/www/.ssh
    nginx:
        build: nginx
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 8081:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    redis:
        image: redis:alpine
    varnish:
        image: million12/varnish
        links:
            - nginx
        environment:
            VCL_CONFIG: "/etc/varnish/default.vcl"
            CACHE_SIZE: "64m"
            VARNISHD_PARAMS: " -a :80 -p default_ttl=3600 -p default_grace=3600"
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl
        ports:
            - 80:80
